# Generated by Django 2.1.5 on 2019-02-07 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20190207_1907'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Job Number')),
                ('job_created', models.DateTimeField(auto_now_add=True)),
                ('job_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.Customer')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='rides.Ride')),
            ],
            options={
                'ordering': ('job_created',),
            },
        ),
    ]
