# Generated by Django 2.1.5 on 2019-02-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='10'),
            preserve_default=False,
        ),
    ]
