# Generated by Django 2.1.7 on 2019-02-12 14:07

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('jobs', '0002_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_images', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
