# Generated by Django 2.1.5 on 2019-02-07 12:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_company', models.CharField(max_length=254, unique=True)),
                ('customer_phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
            options={
                'ordering': ('customer_name',),
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('ride_name',),
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_rides',
            field=models.ManyToManyField(related_name='customers', to='customers.Ride'),
        ),
    ]
