# Generated by Django 2.1.5 on 2019-02-07 19:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190207_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone Number'),
        ),
    ]
